// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NUH_PORTAL.Data;

#nullable disable

namespace NUH_PORTAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720120109_initalDb")]
    partial class initalDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NUH_PORTAL.Models.ADConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("IX_ADConfiguration_config_key")
                        .HasFilter("[config_key] IS NOT NULL");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ADConfiguration", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.AccountLifecycleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("performed_at");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("int")
                        .HasColumnName("performed_by");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("AccountLifecycleLogs", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.AuditChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditLogId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId");

                    b.ToTable("AuditChangeLogs", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("action_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("target_id")
                        .HasColumnType("int");

                    b.Property<string>("target_table")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_agent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.BulkRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValidCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BulkRequests", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.BulkRequestStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BulkRequestId")
                        .HasColumnType("int");

                    b.Property<string>("College")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BulkRequestId");

                    b.ToTable("BulkRequestStudents", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.HousingTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attachment_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("custom_reason");

                    b.Property<string>("NewApartment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_apartment");

                    b.Property<string>("NewBuilding")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_building");

                    b.Property<string>("NewRoom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_room");

                    b.Property<string>("OldApartment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_apartment");

                    b.Property<string>("OldBuilding")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_building");

                    b.Property<string>("OldRoom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_room");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("student_number");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("HousingTransfers", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recipient_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("request_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("sent_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.OTPVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("mobile");

                    b.Property<string>("OTPHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("otp_hash");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_OTPVerifications_expires")
                        .HasFilter("[verified_at] IS NULL");

                    b.HasIndex("Mobile", "VerifiedAt")
                        .HasDatabaseName("IX_OTPVerifications_mobile_verified");

                    b.ToTable("OTPVerifications", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BulkRequestId")
                        .HasColumnType("int")
                        .HasColumnName("bulk_request_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompletedBy")
                        .HasColumnType("int")
                        .HasColumnName("completed_by");

                    b.Property<string>("CyberNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cyber_notes");

                    b.Property<DateTime?>("CyberReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cyber_reviewed_at");

                    b.Property<int?>("CyberReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("cyber_reviewed_by");

                    b.Property<string>("HousingNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("housing_notes");

                    b.Property<DateTime?>("HousingReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("housing_reviewed_at");

                    b.Property<int?>("HousingReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("housing_reviewed_by");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("ReadyForProvisioningAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ready_for_provisioning_at");

                    b.Property<int?>("ReadyForProvisioningBy")
                        .HasColumnType("int")
                        .HasColumnName("ready_for_provisioning_by");

                    b.Property<string>("RegistrationData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_data");

                    b.Property<string>("RequestNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("request_number");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_type");

                    b.Property<string>("RequestedByRole")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requested_by_role");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnType("int")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Requests_request_number")
                        .HasFilter("[request_number] IS NOT NULL");

                    b.HasIndex("StudentId");

                    b.ToTable("Requests", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.RequestAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_type");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("RequestId", "IsDeleted")
                        .HasDatabaseName("IX_RequestAttachments_request_deleted");

                    b.ToTable("RequestAttachments", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.SMSLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SMSLogs_status");

                    b.ToTable("SMSLogs", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RestoredBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RestoredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("academic_level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_extension_academic_level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_extension_apartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_extension_building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_extension_college")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_extension_department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_extension_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_extension_room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ad_last_sync_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ad_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apartment_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("college")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name_english")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("housing_building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("national_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("room_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("student_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("national_id")
                        .IsUnique()
                        .HasFilter("[national_id] IS NOT NULL");

                    b.HasIndex("student_id")
                        .IsUnique()
                        .HasFilter("[student_id] IS NOT NULL");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.StudentDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("accepted_date");

                    b.Property<bool>("DeclarationAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("declaration_accepted");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("PolicyAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("policy_accepted");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("policy_version");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("StudentDeclarations", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.StudentStatusAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ADActionCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ADActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PendingADAction")
                        .HasColumnType("bit");

                    b.Property<string>("StatusType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentStatusActions", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.StudentStatusAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("StudentStatusActionId")
                        .HasColumnType("int")
                        .HasColumnName("student_status_action_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("StudentStatusActionId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("StudentStatusAttachments", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password_hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.WorkflowHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionBy")
                        .HasColumnType("int")
                        .HasColumnName("action_by");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("action_date");

                    b.Property<string>("FromStage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("from_stage");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<string>("ToStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_stage");

                    b.HasKey("Id");

                    b.HasIndex("ActionBy");

                    b.HasIndex("RequestId", "ActionDate")
                        .HasDatabaseName("IX_WorkflowHistory_request_date");

                    b.ToTable("WorkflowHistory", (string)null);
                });

            modelBuilder.Entity("NUH_PORTAL.Models.ADConfiguration", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.AccountLifecycleLog", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NUH_PORTAL.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.AuditChangeLog", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.AuditLog", "AuditLog")
                        .WithMany("AuditChangeLogs")
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditLog");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.AuditLog", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.BulkRequestStudent", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.BulkRequest", "BulkRequest")
                        .WithMany("Students")
                        .HasForeignKey("BulkRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BulkRequest");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.HousingTransfer", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NUH_PORTAL.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.Request", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.RequestAttachment", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NUH_PORTAL.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.StudentDeclaration", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.StudentStatusAction", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NUH_PORTAL.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.StudentStatusAttachment", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.StudentStatusAction", "StudentStatusAction")
                        .WithMany()
                        .HasForeignKey("StudentStatusActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NUH_PORTAL.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentStatusAction");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.WorkflowHistory", b =>
                {
                    b.HasOne("NUH_PORTAL.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActionBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NUH_PORTAL.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.AuditLog", b =>
                {
                    b.Navigation("AuditChangeLogs");
                });

            modelBuilder.Entity("NUH_PORTAL.Models.BulkRequest", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
